def get_metadata_preprocessing() -> str:
    print("Using DUMMY metadata preprocessing instructions.")
    return (
        "SATELLITE DATA\n"
        "- Satellite Pepito: multispectral imagery, resolution 10m, swat 10km, bands: B1, B2, B3, B4.\n"
        "    - B1: Coastal aerosol\n"
        "    - B2: Blue\n"
        "    - B3: Green\n"
        "    - B4: Red\n"
        "    - Product details:\n"
        "        - Folder path: /mnt/data/satellite_pepito/\n"
        "        - Available dates: 2020-01-01 to 2025-12-31\n"
        "        - Available projections: EPSG:4326, EPSG:3857. Names in file replacing ':' with '-'\n"
        "        - Native projection: EPSG:4326\n"
        "        - Available resolutions: 5m, 10m, 20m, 30m\n"
        "        - Native resolution: 10m\n"
        "        - Sub-Product folder: pepito_<band>_<proj>_<res>m\n"
        ""
        "- Satellite Juancito: multispectral imagery, resolution 500m, swat 200km, bands: B1, B2, B3, B4, B5.\n"
        "    - B1: Coastal aerosol\n"
        "    - B2: Blue\n"
        "    - B3: Green\n"
        "    - B4: Red\n"
        "    - B5: Near Infrared\n"
        "    - Product details:\n"
        "        - Folder path: /mnt/data/satellite_juancito/\n"
        "        - Available dates: 2000-01-01 to 2025-12-31\n"
        "        - Available projections: EPSG:4326, EPSG:3857\n"
        "        - Native projection: EPSG:4326\n"
        "        - Available resolutions: 250m, 500m, 1km\n"
        "        - Native resolution: 500m\n"
        "        - Sub-Product folder: juancito_<band>_<proj>_<res>\n"
        "VECTOR DATA (GeoJSON, Geopackage, Shapefile)\n"
        "- No vector data available.\n"
        ""
    )

def get_documentation_preprocessing() -> str:
    print("Using DUMMY documentation preprocessing instructions.")
    return (
        "Preprocessing Functions:\n"
        "- cloud_masking(product_id: str) -> str: Applies cloud masking to the specified product.\n"
        "- atmospheric_correction(product_id: str) -> str: Performs atmospheric correction on the specified product.\n"
        "- resample(product_id: str, target_res: float) -> str: Resamples the product to the target resolution.\n"
        "- reproject(product_id: str, target_proj: str) -> str: Reprojects the product to the target projection.\n"
        ""
        "Satellite Pepito information:\n"
        "- Used for high-resolution land cover mapping\n"
        "- Commonly used in agriculture, forestry, and urban planning applications\n"
        ""
        "Satellite Juancito information:\n"
        "- Used for large-scale environmental monitoring\n"
        "- Commonly used in climate studies, deforestation tracking, and disaster management\n"
        ""
        "Optimization notes:\n"
        "- Make sure to use the same level of preprocessing for all products involved in a geoprocessing task."
        "  Regarding the initial step of preprocessing, the final preprocessing level must be the highest one among the involved products."
    )