def get_metadata_geoprocessing() -> str:
    return (
        "---------- INIT of METADATA of GEOPROCESSING ----------\n"
        "Available GEE geoprocesses (inputs → output → usefulness):\n"
        "\n"
        "1) rgb_single — Single-date RGB GeoTIFF\n"
        "   Inputs: product, bands='R,G,B', bbox='xmin,ymin,xmax,ymax', date, "
        "resolution, projection, apply_cloud_mask (true/false), apply_scale_offset (true/false), "
        "'max_tiles(int)'.\n"
        "   Output: List of GeoTIFF (3 bands). tile URLs + meta (crs, crs_transform, rows, cols).\n"
        "   Usefulness: visual true color or false color at desired res / crs.\n"
        "\n"
        "2) index_single — Single-date normalized difference GeoTIFF\n"
        "   Inputs: product, band1, band2, bbox, date, palette (ignored for TIF), "
        "resolution, projection, apply_cloud_mask (true/false), apply_scale_offset (true/false), "
        "'max_tiles(int)'.\n"
        "   Output: List of GeoTIFF (1 band). tile URLs + meta (crs, crs_transform, rows, cols).\n"
        "   Usefulness: Normalized Difference indexes (e.g., NDVI, NDWI) at desired res / crs.\n"
        "\n"
        "3) rgb_composite — RGB composite (avoids 48 MB/request cap)\n"
        "   Inputs: product, bands, bbox, start, end, reducer, resolution, projection, "
        "apply_cloud_mask (true/false), apply_scale_offset (true/false), "
        "'max_tiles(int)'.\n"
        "   Output: List of GeoTIFF (3 bands) tile URLs + meta (crs, crs_transform, rows, cols).\n"
        "   Usefulness: visual true color or false color at desired res / crs, from reduced-date composites.\n"
        "\n"
        "4) index_composite — ND composite\n"
        "   Inputs: product, band1, band2, bbox, start, end, reducer, resolution, projection, "
        "apply_cloud_mask (true/false), apply_scale_offset (true/false), "
        "'max_tiles(int)'.\n"
        "   Output: List of GeoTIFF (1 band) tile URLs + meta (crs, crs_transform, rows, cols).\n"
        "   Usefulness: Normalized Difference indexes (e.g., NDVI, NDWI) at desired res / crs, from reduced-date composites.\n"
        "\n"
        "5) bands_single — Single-date multi-band GeoTIFF\n"
        "   Inputs: product, bands (optional, comma-separated; empty/None → all bands), "
        "bbox, date, resolution, projection, apply_cloud_mask (true/false), apply_scale_offset (true/false), "
        "'max_tiles(int)'.\n"
        "   Output: List of GeoTIFF (N bands) tile URLs + meta (crs, crs_transform, rows, cols).\n"
        "   Usefulness: export 1–N raw bands (or all bands).\n"
        "\n"
        "6) bands_composite — Multi-date multi-band composite\n"
        "   Inputs: product, bands (optional, comma-separated; empty/None → all bands), "
        "bbox, start, end, reducer, resolution, projection, apply_cloud_mask (true/false), apply_scale_offset (true/false), "
        "'max_tiles(int)'.\n"
        "   Output: List of GeoTIFF (N bands) tile URLs + meta (crs, crs_transform, rows, cols).\n"
        "   Usefulness: same as bands_single but from multi-date composites (mean/median/min/max/mosaic).\n"
        "\n\n"
        "Input tips:\n"
        "- 'product' must be unique, a single product a a time, string variable.\n"
        "- 'resolution=\"default\"' uses the product’s native nominal scale or \"float\" meters (no not put units, only number, e.g., 10).\n"
        "- 'projection=\"default\"' uses the product’s native CRS or \"string\" EPSG code.\n"
        "- 'apply_cloud_mask=true' applies basic cloud masking per product; 'false' uses raw data.\n"
        "- 'apply_scale_offset=true' applies scale and offset to reflectance/temperature bands; 'false' uses raw digital numbers.\n"
        "- 'max_tiles=int' can be adjusted only after initial error and user confirmation.\n"
        "- If resolution is explicitly in meters, UTM projections are preferred for best results (choose zone accordingly).\n"
        "- If resolution is explicitly in degrees, EPSG:4326 is preferred.\n"
        "- If projection is explicitly mentioned, but resolution is in other units, estimate best matching resolution in the target CRS units.\n"
        "---------- END of METADATA of GEOPROCESSING ----------\n"
    )


def get_documentation_geoprocessing() -> str:
    # When to use each geoprocess (short and focused).
    return (
        "---------- INIT of DOCUMENTATION of GEOPROCESSING ----------\n"
        "When to use each geoprocess:\n"
        "- rgb_single: single-day quicklook/export over small–medium areas at specific date.\n"
        "- index_single: single-day ND (e.g., NDVI/NDWI) over small–medium areas.\n"
        "- rgb_composite: multi-date RGB (mean/median/min/max/mosaic) to reduce clouds.\n"
        "- index_composite:  multi-date ND composites (e.g., seasonal NDVI).\n"
        "- bands_single: export 1–N raw bands (or all bands) for a single date over an area.\n"
        "- bands_composite: export 1–N raw bands (or all bands) from multi-date composites for an area.\n"
        "\n Error handling notes:"
        "- If you get 'max_tiles' error from GEE, always suggest changing 'max_tiles' parameter to a higher value while do not mention the technical name of the parameter.\n"
        "- If you are using Sentinel-2 or Landsat products for a single date, it is extremely likely to get a 'ee.ee_exception.EEException: Expression evaluates to an image with no bands.' because there is no image for that date in that area (due to clouds or no acquisition). In that case, suggest to the user to use a date range (start, end) instead of a single date.\n"
        "\n General notes:"
        "- None of the geoprocess uses the key 'other_params'. Leave it empty like other_params={}.\n"
        "- If the resolution and projection are the default/original from MODIS, say to the user that they need to add the following CRS in proj4 format to properly visualize the data: '+proj=sinu +lon_0=0 +x_0=0 +y_0=0 +R=6371007.181 +units=m +no_defs'.\n"
        "- If you specify a resolution, you must also specify a projection that matches the resolution units.\n"
        "- If you specify a projection, you must also specify a resolution that matches the projection units.\n"
        "---------- END of DOCUMENTATION of GEOPROCESSING ----------\n"
    )
