def get_metadata_geoprocessing() -> str:
    return (
        "Available GEE geoprocesses (inputs → output → usefulness):\n"
        "\n"
        "1) rgb_tif — Single-date RGB GeoTIFF\n"
        "   Inputs: product, bands='R,G,B', bbox='xmin,ymin,xmax,ymax', date, "
        "resolution (meters or 'default'), projection (CRS or 'default').\n"
        "   Output: GeoTIFF (3 bands). Usefulness: quick visual/export at chosen res/CRS.\n"
        "\n"
        "2) index_tif — Single-date normalized difference GeoTIFF\n"
        "   Inputs: product, band1, band2, bbox, date, palette (ignored for TIF), "
        "resolution, projection.\n"
        "   Output: GeoTIFF (1 band). Usefulness: NDVI/NDWI-type rasters.\n"
        "\n"
        "3) rgb_composite_tif — Date-range RGB with reducer\n"
        "   Inputs: product, bands='R,G,B', bbox, start, end, reducer (mean|min|max|median|mosaic), "
        "resolution, projection.\n"
        "   Output: GeoTIFF (3 bands). Usefulness: cloud-robust RGB mosaics.\n"
        "\n"
        "4) index_composite_tif — Date-range ND with reducer\n"
        "   Inputs: product, band1, band2, bbox, start, end, reducer, resolution, projection.\n"
        "   Output: GeoTIFF (1 band). Usefulness: composited indices.\n"
        "\n"
        "5) rgb_composite_tif_tiled — Tiled RGB composite (avoids 48 MB/request cap)\n"
        "   Inputs: product, bands, bbox, start, end, reducer, resolution, projection, "
        "tile_size (px edge), max_tiles (optional).\n"
        "   Output: List of GeoTIFF tile URLs + tiling meta (crs, crs_transform, rows, cols).\n"
        "   Usefulness: large areas at native res without changing analytics; tiles align perfectly "
        "via fixed grid (constant CRS+crs_transform).\n"
        "\n"
        "6) index_composite_tif_tiled — Tiled ND composite\n"
        "   Inputs: product, band1, band2, bbox, start, end, reducer, resolution, projection, "
        "tile_size (px edge), max_tiles (optional).\n"
        "   Output: List of GeoTIFF tile URLs + tiling meta.\n"
        "   Usefulness: large single-band outputs at high resolution.\n"
        "\n"
        "Input tips:\n"
        "- 'resolution=default' uses the product’s native nominal scale; "
        "'projection=default' uses the product’s native CRS.\n"
        "- 'tile_size' is in pixels per tile edge. Typical safe values: RGB=2048, Index=3072. "
        "Each tile must be ≤ ~48 MB and ≤ 10k px per side.\n"
    )


def get_documentation_geoprocessing() -> str:
    # When to use each geoprocess (short and focused).
    return (
        "When to use each geoprocess:\n"
        "- rgb_tif: single-day quicklook/export over small–medium areas at specific date.\n"
        "- index_tif: single-day ND (e.g., NDVI/NDWI) over small–medium areas.\n"
        "- rgb_composite_tif: multi-date RGB (mean/median/min/max/mosaic) to reduce clouds; medium areas.\n"
        "- index_composite_tif: multi-date ND composites (e.g., seasonal NDVI); medium areas.\n"
        "- rgb_composite_tif_tiled: same as rgb_composite_tif but for **large areas**; set tile_size to keep per-tile size under limits while preserving resolution.\n"
        "- index_composite_tif_tiled: same as index_composite_tif for **large areas**; use larger tile_size than RGB when feasible (1 band).\n"
    )
